# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetAuth(object):
    def setupUi(self, widgetAuth):
        widgetAuth.setObjectName("widgetAuth")
        widgetAuth.resize(203, 95)
        self.verticalLayout = QtWidgets.QVBoxLayout(widgetAuth)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(widgetAuth)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.inputEmail = QtWidgets.QLineEdit(widgetAuth)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputEmail)
        self.label_2 = QtWidgets.QLabel(widgetAuth)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.inputPassword = QtWidgets.QLineEdit(widgetAuth)
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPassword.setObjectName("inputPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputPassword)
        self.verticalLayout.addLayout(self.formLayout)
        self.btnLogin = QtWidgets.QPushButton(widgetAuth)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)

        self.retranslateUi(widgetAuth)
        QtCore.QMetaObject.connectSlotsByName(widgetAuth)

    def retranslateUi(self, widgetAuth):
        _translate = QtCore.QCoreApplication.translate
        widgetAuth.setWindowTitle(_translate("widgetAuth", "Authenticate"))
        self.label.setText(_translate("widgetAuth", "Email"))
        self.label_2.setText(_translate("widgetAuth", "Password"))
        self.btnLogin.setText(_translate("widgetAuth", "Login"))
